name: To prod
# Тригеры для сработки
on:
  release:
    types: [published]

jobs:
  build_and_send_to_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install java (11)
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: name
        run: sudo apt-get update -y
      - name: Install dos2unix
        run: sudo apt-get install -y dos2unix
      - name: Convert file
        run: dos2unix ./gradlew
      - name: Make executable
        run: chmod +x ./gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build application
        run: ./gradlew build -x test
      - name: Copy .jar file
        run: mv ./build/libs/octopus-0.0.1-SNAPSHOT.jar ./octopus.jar
      - name: login docker
        run: echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - name: build container
        run: docker build -t anarcom/joust-backend:${GITHUB_REF:11} -t anarcom/joust-backend:latest -f Dockerfile .
      - name: push container
        run: docker image push --all-tags anarcom/joust-backend